Home page
benshidanny11/portforio pull request #1
Opened 2021-08-11 16:45 UTC by benshidanny11

## Home page

In this project, I
- Added Home page  
- Implemented Responsiveness

2021-08-11 19:10 UTC, karvel-code requested changes
Hi @benshidanny11 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Gitflow has been adhered to.
- All linter checks pass successfully.

## Required Changes ♻️
_Check the comments under the review._
 

- [ ] Please ensure to wrap the hamburger menu/icon inside the `<nav>` tag. This enhances the semantics of your HTML code. In this case, you could change the `<div>` on line 23 to a `<nav>` tag.
- [ ] Please ensure to wrap the code for the toolbar inside the `<header>` tag.
- [ ] Please ensure to add this image as a background image and not as a normal image wrapped using the `<img>` tag.
- [ ] Please wrap the icons in the main section with the `<ul>` tag and `<li>` to wrap the contents(each icon) of the `<ul>` tag. Also, ensure that each icon is a link or wrapped inside the `<a>` tag.
- [ ] Please ensure to wrap the code in the main section with the `<section>` tag. This improves the semantics of your HTML code.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 19:10 UTC, karvel-code commented on home.html
> +      <!-- End header section -->
- [ ] Please ensure to wrap the code for the toolbar inside the `<header>` tag. For example, you could replace the `<div>` tag at line 13 with the `<header>` tag. Doing this will ensure to enhance the semantics of your HTML code.

2021-08-11 19:10 UTC, karvel-code commented on home.html
> +          <h3 class="logo">My logo</h3>
Please ensure that your logo is wrapped inside the `<a>` tag or is a link. This is so as to follow the project requirements.

2021-08-11 19:10 UTC, karvel-code commented on home.html
> +          </div>
- [ ] Ensure to wrap the hamburger menu/icon inside the `<nav>` tag. This enhances the semantics of your HTML code. In this case, you could change the `<div>` on line 23 to a `<nav>` tag.

2021-08-11 19:10 UTC, karvel-code commented on home.html
> +      <!-- End content section -->
- [ ] Please ensure to wrap the code in this section with the `<section>` tag. This improves the semantics of your HTML code.

2021-08-11 19:10 UTC, karvel-code commented on home.html
> +        </div>
- [ ] Please ensure to add this image as a background image and not as a normal image wrapped using the `<img>` tag.

2021-08-11 19:10 UTC, karvel-code commented on home.html
> +        </div>
- [ ] Please wrap the icons in this section with the `<ul>` tag and `<li>` to wrap the contents(each icon) of the `<ul>` tag. 
- [ ] Also, ensure that each icon is a link or wrapped inside the `<a>` tag.

2021-08-12 06:51 UTC, DanteAlonsoHT requested changes
<h1>Status: Changes Required 🚫 ♻️  </h1>

Hi @benshidanny11, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

_Check the comments under the review._

<hr>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-12 06:51 UTC, DanteAlonsoHT commented on .gitignore
> +package-lock.json
- [ ]  Kindly remove the `package-lock.json` from the `.gitignore` file.

2021-08-12 06:51 UTC, DanteAlonsoHT commented on README.md
>  > The second project in microverse.
I know you can do a better effort to make an impressive README file. You should use the [Template provided by Microverse](https://github.com/microverseinc/readme-template) for this and all of your next projects in Microverse. Feel free to check [This Example](https://github.com/DanteAlonsoHT/awesome_books_js) about what we expect to see in your README files.

- [ ] Make an impressive README file.

2021-08-12 08:23 UTC, AshakaE approved these changes
### Hi @benshidanny11  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 08:23 UTC, AshakaE commented on README.md
>  # Portforio
[OPTIONAL]
- [ ] Please correct this typo in your README file, I believe it's `Portfolio` not `Portforio` 🙏

2021-08-12 08:39 UTC, merged